# Generated by Django 5.0.9 on 2026-06-22 09:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    def create_branding_for_existing_sites(apps, schema_editor):
        Site = apps.get_model('sites', 'Site')
        SiteBranding = apps.get_model('site_branding', 'SiteBranding')
        for site in Site.objects.all():
            SiteBranding.objects.get_or_create(site=site)

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, help_text='Upload a favicon (PNG or ICO, 48×48 recommended).', null=True, upload_to='sajilowork/site/favicons/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'svg'])])),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site favicon',
                'verbose_name_plural': 'Site favicons',
            },
        ),
        migrations.RunPython(create_branding_for_existing_sites, migrations.RunPython.noop),
    ]
