# Generated by Django 5.0.9 on 2026-06-22 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_branding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebranding',
            name='favicon',
            field=models.FileField(blank=True, help_text='Upload a favicon (PNG or ICO, 48×48 recommended).', null=True, upload_to='sajilowork/site/favicons/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'svg'])]),
        ),
    ]
