# Generated by Django 5.0.9 on 2026-06-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_branding', '0002_alter_sitebranding_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitebranding',
            name='favicon',
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='favicon_url',
            field=models.URLField(blank=True, default='', help_text='Cloudinary URL for the site favicon (PNG or ICO, 48×48 recommended).'),
        ),
    ]
