# Generated by Django 5.0.9 on 2026-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_branding', '0003_remove_sitebranding_favicon_sitebranding_favicon_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitebranding',
            options={'verbose_name': 'Site branding', 'verbose_name_plural': 'Site branding'},
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Public support email for Organization schema and contact pages.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='Default meta description for search engines and social sharing.', max_length=320),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='og_image_url',
            field=models.URLField(blank=True, default='', help_text='Default Open Graph image URL (1200×630 recommended).'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', help_text='Twitter/X handle without @ (e.g. sajilowork).', max_length=50),
        ),
    ]
