# Generated by Django 5.0.9 on 2026-05-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskactivity',
            new_name='task_activi_task_id_e45ba7_idx',
            old_name='task_activi_task_id_ad7e94_idx',
        ),
        migrations.RenameIndex(
            model_name='taskactivity',
            new_name='task_activi_activit_d2926a_idx',
            old_name='task_activi_activit_4b34d2_idx',
        ),
    ]
