# Generated by Django 5.1.4 on 2026-05-19 10:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Search query text', max_length=500, unique=True)),
                ('search_count', models.IntegerField(default=1, help_text='Number of times searched', validators=[django.core.validators.MinValueValidator(1)])),
                ('click_through_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of searches that resulted in clicks', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_searched_at', models.DateTimeField(auto_now=True, help_text='Last time this query was searched')),
                ('is_trending', models.BooleanField(default=False, help_text='Whether this search is currently trending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Popular Search',
                'verbose_name_plural': 'Popular Searches',
                'db_table': 'popular_searches',
                'ordering': ['-search_count', '-last_searched_at'],
                'indexes': [models.Index(fields=['-search_count', '-last_searched_at'], name='popular_sea_search__6fbee5_idx'), models.Index(fields=['is_trending', '-search_count'], name='popular_sea_is_tren_ab9035_idx'), models.Index(fields=['query'], name='popular_sea_query_9aeed0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Filter combination name', max_length=200)),
                ('filters', models.JSONField(help_text='Filter configuration')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times used', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_preset', models.BooleanField(default=False, help_text='Whether this is a system preset')),
                ('is_active', models.BooleanField(default=True, help_text='Whether filter is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Filter',
                'verbose_name_plural': 'Search Filters',
                'db_table': 'search_filters',
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['is_preset', 'is_active'], name='search_filt_is_pres_94332d_idx'), models.Index(fields=['-usage_count'], name='search_filt_usage_c_84bc1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-defined name for the search', max_length=200)),
                ('query', models.CharField(help_text='Search query text', max_length=500)),
                ('search_type', models.CharField(choices=[('tasks', 'Tasks'), ('taskers', 'Taskers'), ('categories', 'Categories')], default='tasks', help_text='Type of search', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Applied filters (category, location, budget, etc.)')),
                ('notify_new_results', models.BooleanField(default=True, help_text='Send notifications for new matching results')),
                ('notification_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='daily', help_text='How often to send notifications', max_length=20)),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='Last time user was notified', null=True)),
                ('last_result_count', models.IntegerField(default=0, help_text='Number of results in last check', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether search is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who saved the search', on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'db_table': 'saved_searches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='saved_searc_user_id_fc38f3_idx'), models.Index(fields=['user', 'is_active'], name='saved_searc_user_id_2b1034_idx'), models.Index(fields=['notify_new_results', 'is_active'], name='saved_searc_notify__01cdcf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Search query text', max_length=500)),
                ('search_type', models.CharField(choices=[('tasks', 'Tasks'), ('taskers', 'Taskers'), ('categories', 'Categories'), ('all', 'All')], default='tasks', help_text='Type of search performed', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Applied filters (category, location, budget, etc.)')),
                ('results_count', models.IntegerField(default=0, help_text='Number of results returned', validators=[django.core.validators.MinValueValidator(0)])),
                ('clicked_result', models.BooleanField(default=False, help_text='Whether user clicked on any result')),
                ('clicked_result_id', models.IntegerField(blank=True, help_text='ID of clicked result', null=True)),
                ('clicked_result_type', models.CharField(blank=True, help_text='Type of clicked result (task, tasker, category)', max_length=20, null=True)),
                ('session_id', models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of searcher', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the search (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_hist_user_id_3ea0ad_idx'), models.Index(fields=['query', '-created_at'], name='search_hist_query_b74509_idx'), models.Index(fields=['search_type', '-created_at'], name='search_hist_search__d46f38_idx'), models.Index(fields=['session_id', '-created_at'], name='search_hist_session_cedc57_idx'), models.Index(fields=['-created_at'], name='search_hist_created_e154e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Suggested search query', max_length=500, unique=True)),
                ('priority', models.IntegerField(default=0, help_text='Display priority (higher = shown first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether suggestion is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Related category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_suggestions', to='tasks.category')),
            ],
            options={
                'verbose_name': 'Search Suggestion',
                'verbose_name_plural': 'Search Suggestions',
                'db_table': 'search_suggestions',
                'ordering': ['-priority', 'query'],
                'indexes': [models.Index(fields=['is_active', '-priority'], name='search_sugg_is_acti_8faf09_idx'), models.Index(fields=['query'], name='search_sugg_query_8264b1_idx')],
            },
        ),
    ]
