# Generated by Django 5.0.9 on 2026-05-26 09:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_initial'),
        ('payments', '0002_add_esewa_payment_method'),
        ('tasks', '0004_rename_task_activi_task_id_ad7e94_idx_task_activi_task_id_e45ba7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount provider receives after fees', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrows', to='bids.bid')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='payments.payment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrows', to='tasks.task')),
            ],
            options={
                'db_table': 'escrows',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='escrows_status_7c8985_idx'), models.Index(fields=['task'], name='escrows_task_id_dc1239_idx'), models.Index(fields=['bid'], name='escrows_bid_id_6f4a4b_idx')],
            },
        ),
    ]
