# Generated by Django 5.0.9 on 2026-05-27 10:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_nepal_npr_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, help_text='When disabled, no platform fee is deducted on task completion.')),
                ('tasker_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentage deducted from the task payment when crediting the tasker (e.g. 10 = 10%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('poster_service_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional extra % charged to the poster on top of the bid (usually 0).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum platform fee per task (NPR). 0 = no minimum.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_platform_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum platform fee per task (NPR). Leave empty for no cap.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('apply_processing_fee_on_wallet', models.BooleanField(default=False, help_text='Apply card-style processing fees for wallet escrow payments (usually off for NPR).')),
                ('wallet_processing_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('wallet_processing_fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('card_processing_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('2.90'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('card_processing_fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admins (not shown to users).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform fee settings',
                'verbose_name_plural': 'Platform fee settings',
                'db_table': 'platform_fee_settings',
            },
        ),
    ]
