# Generated by Django 5.0.9 on 2026-05-27 11:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_platform_fee_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeWebhookEvent',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_stripe__6cb0ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentmethod',
            name='payment_met_stripe__52abfb_idx',
        ),
        migrations.RemoveIndex(
            model_name='payout',
            name='payouts_stripe__0e5af4_idx',
        ),
        migrations.RemoveIndex(
            model_name='refund',
            name='refunds_stripe__323b59_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_method_id',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='stripe_payment_method_id',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='stripe_payout_id',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='stripe_refund_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet Balance'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank_account', 'Bank Account'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_processing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payment processor fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('bank_account', 'Bank Account'), ('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=20),
        ),
    ]
