# Generated by Django 5.1.4 on 2026-05-19 10:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 code', max_length=2, unique=True)),
                ('code3', models.CharField(help_text='ISO 3166-1 alpha-3 code', max_length=3, unique=True)),
                ('phone_code', models.CharField(help_text='International dialing code', max_length=10)),
                ('currency_code', models.CharField(help_text='ISO 4217 currency code', max_length=3)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'locations_countries',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='locations_c_code_c98a99_idx'), models.Index(fields=['is_active'], name='locations_c_is_acti_667602_idx')],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='State/Province code', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='locations.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'locations_states',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('population', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Popular cities shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.state')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'locations_cities',
                'ordering': ['-is_popular', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(help_text="Custom label (e.g., 'Mom's House')", max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_locations', to='locations.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Location',
                'verbose_name_plural': 'User Locations',
                'db_table': 'locations_user_locations',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('query', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('radius', models.IntegerField(blank=True, null=True)),
                ('results_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Search',
                'verbose_name_plural': 'Location Searches',
                'db_table': 'locations_location_searches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='locations_l_user_id_4859a8_idx'), models.Index(fields=['session_id', '-created_at'], name='locations_l_session_1149cd_idx'), models.Index(fields=['-created_at'], name='locations_l_created_a5aff4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('radius', models.IntegerField(default=10, help_text='Service radius in kilometers', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='locations.city')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'tasker'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'db_table': 'locations_service_areas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='locations_s_user_id_c370ae_idx'), models.Index(fields=['city', 'is_active'], name='locations_s_city_id_82178c_idx')],
                'unique_together': {('user', 'city')},
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country', 'code'], name='locations_s_country_1bd06a_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['is_active'], name='locations_s_is_acti_b0f30f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'code')},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'name'], name='locations_c_state_i_b83fba_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active'], name='locations_c_is_acti_6529bf_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_popular'], name='locations_c_is_popu_5f8402_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['latitude', 'longitude'], name='locations_c_latitud_c0fd9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user', 'location_type'], name='locations_u_user_id_5d626a_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user', 'is_default'], name='locations_u_user_id_d61403_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='locations_u_latitud_1ad1b2_idx'),
        ),
    ]
