# Generated by Django 5.0.9 on 2026-05-21 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image', null=True, upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image', null=True, upload_to='profile_images/'),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.URLField(help_text='URL to the portfolio file')),
                ('file_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('thumbnail', models.URLField(blank=True, help_text='Thumbnail URL for images', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_items',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['user', 'order'], name='portfolio_i_user_id_469f3a_idx')],
            },
        ),
    ]
