# Generated by Django 5.0.9 on 2026-05-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_cover_image_alter_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_payment_method',
            field=models.BooleanField(default=False, help_text='Whether user has linked a payment method'),
        ),
    ]
