# Generated by Django 5.1.5 on 2026-05-19 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], max_length=20)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Uploads',
                'db_table': 'uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('thumbnail_small', models.ImageField(blank=True, help_text='150x150 thumbnail', null=True, upload_to='thumbnails/small/%Y/%m/%d/')),
                ('thumbnail_medium', models.ImageField(blank=True, help_text='300x300 thumbnail', null=True, upload_to='thumbnails/medium/%Y/%m/%d/')),
                ('thumbnail_large', models.ImageField(blank=True, help_text='600x600 thumbnail', null=True, upload_to='thumbnails/large/%Y/%m/%d/')),
                ('format', models.CharField(blank=True, max_length=10)),
                ('color_mode', models.CharField(blank=True, max_length=20)),
                ('has_transparency', models.BooleanField(default=False)),
                ('is_optimized', models.BooleanField(default=False)),
                ('thumbnails_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_data', to='uploads.upload')),
            ],
            options={
                'verbose_name': 'Image Upload',
                'verbose_name_plural': 'Image Uploads',
                'db_table': 'image_uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word Document'), ('docx', 'Word Document (DOCX)'), ('xls', 'Excel Spreadsheet'), ('xlsx', 'Excel Spreadsheet (XLSX)'), ('ppt', 'PowerPoint Presentation'), ('pptx', 'PowerPoint Presentation (PPTX)'), ('txt', 'Text File'), ('csv', 'CSV File'), ('other', 'Other')], max_length=20)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text content')),
                ('text_extracted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_data', to='uploads.upload')),
            ],
            options={
                'verbose_name': 'Document Upload',
                'verbose_name_plural': 'Document Uploads',
                'db_table': 'document_uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_quota', models.BigIntegerField(default=1073741824, help_text='Total storage quota in bytes')),
                ('used_quota', models.BigIntegerField(default=0, help_text='Used storage in bytes')),
                ('max_files', models.IntegerField(default=1000, help_text='Maximum number of files')),
                ('file_count', models.IntegerField(default=0, help_text='Current number of files')),
                ('last_reset', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Quota',
                'verbose_name_plural': 'Upload Quotas',
                'db_table': 'upload_quotas',
            },
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['user', '-created_at'], name='uploads_user_id_3bd8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['content_type', 'object_id'], name='uploads_content_0917ea_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['file_type', 'status'], name='uploads_file_ty_3ebedf_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['is_active'], name='uploads_is_acti_f82fa2_idx'),
        ),
    ]
