# Generated by Django 5.0.1 on 2026-05-19 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='tasker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidmessage',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bids.bid'),
        ),
        migrations.AddField(
            model_name='bidmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidnotification',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bids.bid'),
        ),
        migrations.AddField(
            model_name='bidnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidreview',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bids.bid'),
        ),
        migrations.AddField(
            model_name='bidreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['task', 'status'], name='bids_task_id_cd6dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['tasker', 'status'], name='bids_tasker__4dc5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['created_at'], name='bids_created_ec08db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('task', 'tasker')},
        ),
        migrations.AddIndex(
            model_name='bidnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='bid_notific_recipie_5d5b8e_idx'),
        ),
    ]
