# Generated by Django 5.0.9 on 2026-05-27 10:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0005_platform_fee_settings'),
        ('tasks', '0005_nepal_npr_budget_currency'),
        ('wallets', '0002_nepal_npr_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('fee_type', models.CharField(choices=[('COMMISSION', 'Commission (platform cut from worker)'), ('ESCROW', 'Escrow / service fee (charged to customer)'), ('WITHDRAWAL', 'Withdrawal fee'), ('CANCELLATION', 'Cancellation fee'), ('TAX', 'Tax fee'), ('DISCOUNT', 'Discount / promo adjustment')], db_index=True, max_length=20)),
                ('value_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of base amount'), ('FIXED', 'Fixed amount')], max_length=12)),
                ('value', models.DecimalField(decimal_places=4, help_text='Percentage (e.g. 10 = 10%) or fixed NPR amount depending on value type.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Higher priority wins when multiple rules match the same fee type.')),
                ('min_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum resulting fee amount (NPR).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum resulting fee amount (NPR).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_base_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Rule applies only if transaction base amount is at least this.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_base_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Rule applies only if transaction base amount is at most this.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('user_tier', models.CharField(blank=True, help_text='Optional tier slug (e.g. bronze, silver). Blank = all tiers.', max_length=32)),
                ('cancellation_stage', models.CharField(blank=True, choices=[('BEFORE_ACCEPT', 'Before bid accepted'), ('AFTER_ACCEPT', 'After bid accepted'), ('IN_PROGRESS', 'Task in progress')], help_text='Only used when fee_type is CANCELLATION.', max_length=20)),
                ('withdrawal_method', models.CharField(blank=True, help_text='esewa, khalti, bank_transfer, etc. Blank = all methods.', max_length=32)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_rules', to='tasks.category')),
            ],
            options={
                'verbose_name': 'Fee rule',
                'verbose_name_plural': 'Fee rules',
                'db_table': 'fee_rules',
                'ordering': ['-priority', 'fee_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_type', models.CharField(db_index=True, max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('rule_snapshot', models.JSONField(blank=True, default=dict, help_text='Copy of rule fields at calculation time for audit.')),
                ('status', models.CharField(choices=[('calculated', 'Calculated (preview)'), ('applied', 'Applied to transaction'), ('reversed', 'Reversed')], db_index=True, default='calculated', max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_transactions', to='payments.payment')),
                ('rule_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fees.feerule')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_transactions', to='tasks.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_transactions', to=settings.AUTH_USER_MODEL)),
                ('withdrawal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_transactions', to='wallets.withdrawalrequest')),
            ],
            options={
                'verbose_name': 'Fee transaction log',
                'verbose_name_plural': 'Fee transaction logs',
                'db_table': 'fee_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feerule',
            index=models.Index(fields=['fee_type', 'is_active', '-priority'], name='fee_rules_fee_typ_0b7abf_idx'),
        ),
        migrations.AddIndex(
            model_name='feerule',
            index=models.Index(fields=['cancellation_stage'], name='fee_rules_cancell_fadaca_idx'),
        ),
        migrations.AddIndex(
            model_name='feerule',
            index=models.Index(fields=['withdrawal_method'], name='fee_rules_withdra_9dbf1f_idx'),
        ),
        migrations.AddIndex(
            model_name='feetransaction',
            index=models.Index(fields=['fee_type', 'status', '-created_at'], name='fee_transac_fee_typ_7cae86_idx'),
        ),
        migrations.AddIndex(
            model_name='feetransaction',
            index=models.Index(fields=['user', '-created_at'], name='fee_transac_user_id_1b8f9a_idx'),
        ),
    ]
