# Generated by GPT-5.2 on 2026-05-28

from decimal import Decimal

from django.db import migrations, models


def migrate_fee_type_values(apps, schema_editor):
    FeeRule = apps.get_model('fees', 'FeeRule')

    mapping = {
        'COMMISSION': 'TASKER_COMMISSION',
        'ESCROW': 'CUSTOMER_SERVICE_FEE',
        'WITHDRAWAL': 'WITHDRAWAL_FEE',
        'CANCELLATION': 'CANCELLATION_FEE',
        'TAX': 'TAX_FEE',
        'DISCOUNT': 'PROMOTIONAL_DISCOUNT',
    }

    for old, new in mapping.items():
        FeeRule.objects.filter(fee_type=old).update(fee_type=new)

    # Best-effort defaults for applies_to.
    FeeRule.objects.filter(fee_type='TASKER_COMMISSION', applies_to='BOTH').update(applies_to='TASKER')
    FeeRule.objects.filter(fee_type='CUSTOMER_SERVICE_FEE', applies_to='BOTH').update(applies_to='CUSTOMER')
    FeeRule.objects.filter(fee_type='WITHDRAWAL_FEE', applies_to='BOTH').update(applies_to='TASKER')
    FeeRule.objects.filter(fee_type='TAX_FEE', applies_to='BOTH').update(applies_to='CUSTOMER')


class Migration(migrations.Migration):
    dependencies = [
        ('fees', '0002_seed_default_fee_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerule',
            name='applies_to',
            field=models.CharField(
                choices=[('CUSTOMER', 'Customer (poster)'), ('TASKER', 'Tasker'), ('BOTH', 'Both')],
                default='BOTH',
                help_text='Who this fee applies to (customer, tasker, or both).',
                max_length=10,
            ),
        ),
        migrations.RenameField(
            model_name='feerule',
            old_name='min_base_amount',
            new_name='min_amount',
        ),
        migrations.RenameField(
            model_name='feerule',
            old_name='max_base_amount',
            new_name='max_amount',
        ),
        migrations.AddField(
            model_name='feerule',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feerule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='feerule',
            name='admin_notes',
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='payer',
            field=models.CharField(blank=True, help_text='Who paid this fee (CUSTOMER/TASKER/...).', max_length=20),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='receiver',
            field=models.CharField(blank=True, help_text='Who received this fee (PLATFORM/...).', max_length=20),
        ),
        migrations.RunPython(migrate_fee_type_values, migrations.RunPython.noop),
    ]

