# Generated by GPT-5.2 on 2026-05-28

from decimal import Decimal

from django.db import migrations


def fix_defaults(apps, schema_editor):
    FeeRule = apps.get_model('fees', 'FeeRule')

    # Only touch the seeded defaults if they exist and are still zero.
    FeeRule.objects.filter(
        name='Default escrow / service fee',
        fee_type='CUSTOMER_SERVICE_FEE',
        value=Decimal('0.0000'),
        value_type='PERCENTAGE',
    ).update(value=Decimal('5.0000'))

    FeeRule.objects.filter(
        name='Default tax',
        fee_type='TAX_FEE',
        value=Decimal('0.0000'),
        value_type='PERCENTAGE',
    ).update(value=Decimal('0.0000'))


class Migration(migrations.Migration):
    dependencies = [
        ('fees', '0003_airtasker_fee_rule_schema'),
    ]

    operations = [
        migrations.RunPython(fix_defaults, migrations.RunPython.noop),
    ]

