# Generated by Django 5.0.9 on 2026-05-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_nepal_npr_currency'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='withdrawalrequest',
            name='withdrawal__stripe__dd5bf2_idx',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='paypal_email',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='stripe_payout_id',
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='withdrawal_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=20),
        ),
    ]
