# Generated by Django 5.1.5 on 2026-05-19 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('steps', models.JSONField(default=list, help_text='List of step names in order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funnel',
                'verbose_name_plural': 'Funnels',
                'db_table': 'analytics_funnels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('user_activity', 'User Activity'), ('task_performance', 'Task Performance'), ('revenue', 'Revenue'), ('engagement', 'Engagement'), ('retention', 'Retention'), ('custom', 'Custom')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'analytics_reports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField(default=dict, help_text='Criteria for cohort membership')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_update', models.BooleanField(default=False, help_text='Automatically update cohort membership')),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, related_name='cohorts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cohort',
                'verbose_name_plural': 'Cohorts',
                'db_table': 'analytics_cohorts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('metric_type', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('histogram', 'Histogram'), ('rate', 'Rate')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('aggregation_period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='Metric dimensions')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'db_table': 'analytics_metrics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['name', '-period_start'], name='analytics_m_name_1920ef_idx'), models.Index(fields=['category', '-period_start'], name='analytics_m_categor_0b29c9_idx'), models.Index(fields=['aggregation_period', '-period_start'], name='analytics_m_aggrega_f60d92_idx')],
                'unique_together': {('name', 'aggregation_period', 'period_start', 'dimensions')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, help_text='Session identifier', max_length=255)),
                ('category', models.CharField(choices=[('user', 'User'), ('task', 'Task'), ('bid', 'Bid'), ('payment', 'Payment'), ('chat', 'Chat'), ('review', 'Review'), ('search', 'Search'), ('notification', 'Notification'), ('system', 'System')], max_length=50)),
                ('event_type', models.CharField(choices=[('user_registered', 'User Registered'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('profile_updated', 'Profile Updated'), ('profile_viewed', 'Profile Viewed'), ('task_created', 'Task Created'), ('task_published', 'Task Published'), ('task_viewed', 'Task Viewed'), ('task_bookmarked', 'Task Bookmarked'), ('task_completed', 'Task Completed'), ('task_cancelled', 'Task Cancelled'), ('bid_submitted', 'Bid Submitted'), ('bid_accepted', 'Bid Accepted'), ('bid_rejected', 'Bid Rejected'), ('bid_withdrawn', 'Bid Withdrawn'), ('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('refund_requested', 'Refund Requested'), ('payout_completed', 'Payout Completed'), ('message_sent', 'Message Sent'), ('conversation_started', 'Conversation Started'), ('review_submitted', 'Review Submitted'), ('review_responded', 'Review Responded'), ('search_performed', 'Search Performed'), ('filter_applied', 'Filter Applied'), ('notification_sent', 'Notification Sent'), ('notification_read', 'Notification Read'), ('error_occurred', 'Error Occurred'), ('api_called', 'API Called')], max_length=50)),
                ('event_name', models.CharField(help_text='Human-readable event name', max_length=255)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Additional event properties')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, help_text='mobile, tablet, desktop', max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_e_user_id_e1a457_idx'), models.Index(fields=['category', 'event_type'], name='analytics_e_categor_f39b36_idx'), models.Index(fields=['session_id'], name='analytics_e_session_b3cbf5_idx'), models.Index(fields=['content_type', 'object_id'], name='analytics_e_content_ab02a6_idx'), models.Index(fields=['-created_at'], name='analytics_e_created_c06122_idx')],
            },
        ),
        migrations.CreateModel(
            name='FunnelStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('step_name', models.CharField(max_length=255)),
                ('step_index', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_steps', to='analytics.funnel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funnel Step',
                'verbose_name_plural': 'Funnel Steps',
                'db_table': 'analytics_funnel_steps',
                'ordering': ['funnel', 'step_index', '-created_at'],
                'indexes': [models.Index(fields=['funnel', 'user'], name='analytics_f_funnel__d734ef_idx'), models.Index(fields=['session_id'], name='analytics_f_session_a648e8_idx'), models.Index(fields=['-created_at'], name='analytics_f_created_c6a7f3_idx')],
            },
        ),
    ]
